### ISSUE TITLE
try fix: get error in the nuxt dev mode

### ISSUE THREAD

**Issue by starknt** [nomorechokedboy/markdown-vue#7]
## I'm submitting a ...

- [x] bug report

## What is the current behavior?
get error in the nuxt dev mode

## What is the expected behavior?
work

**Comment by starknt** [comment]
我现在有一个比较笨的方法尝试修复它

**Comment by nomorechokedboy** [comment]
Currently, the application will be crash if you use this component in Nuxt project dev mode and I can't figure out why this is happening, it works on production build but not dev. Unfortunately, I still can't figure out how to solve this :disappointed:

**Comment by starknt** [comment]
Hello, i try fix it in the #8

**Comment by nomorechokedboy** [comment]
> Hello, i try fix it in the #8

Dude, you're my savior. Thank you for the fix. Can I ask you how did you figure it out. Also, I am trying to install the newest deps, and it works without any error

**Comment by starknt** [comment]
According to the error message, I checked the [debug](https://github.com/debug-js/debug) and found that its export method on the browser is CJS.

**Comment by nomorechokedboy** [comment]
> According to the error message, I checked the [debug](https://github.com/debug-js/debug) and found that its export method on the browser is CJS.

I also found that. However, I don't know how to fix that, didn't think and research about the optimize deps option. Again, thank you for the fix
